import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Eventhub | Landing Page",
    description: "Generated by create next app",
  };


const generateMetadata:React.FC = () => {
    return (

    )
}